version: '3.8'

services:
  survey-api:
    container_name: survey-api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: survey-api
    networks:
      - survey-net
    ports:
      - "7142:80"
    depends_on:
      - survey_db
    restart: always

  survey_db:
    container_name: postgres
    image: postgres:14
    hostname: postgres
    networks:
      - survey-net
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: survey_db
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    hostname: pgadmin4
    networks:
      - survey-net
    ports:
      - "5050:5433"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5433
    depends_on:
      - survey_db
    restart: always

networks:
  survey-net:
    driver: bridge

volumes:
  pg-data: {}
  pgadmin: {}
